backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "cards"
    label: "Business Cards"
    files:
      - file: "cards.json"
        label: "Cards"
        name: "cards"
        fields:
          - label: "Cards"
            name: "cards"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Phone", name: "phone", widget: "string"}
